### ISSUE TITLE
Hashlink support

### ISSUE THREAD

**Issue by nspitko** [shohei909/TypePacker#1]
A simple test case:

```haxe
var foo = Json.print("Float", 1.1);
```

produces this exciting output:

`Error: Extern type not supported : TypePackerResource2`

I can find vanishing little info on this error, but it appears to point towards the `onAfterTyping` class replacement hack. However... I do the same hack in my own code and it doesn't produce this error, so I'm at a bit of a loss as to what might be triggering it.

**Comment by shohei909** [comment]
fixed in 1.3.0
